[Interface]
Address = 10.13.13.2
PrivateKey = 0NZ1B/IZOF1xpfRQ2UWxjY3WJz/iVpPpdSKypiQAAUU=

[Peer]
PublicKey = xRzZkTkpw1GBwLU+KMOMVJDRPq+QdIagQ8lExzxEpCo=
PresharedKey = 3D/I+keVaSItNNwExRDi8LRdI9IzoShSquo9i+MxFo4=
Endpoint = 127.0.0.1:51820
AllowedIPs = 10.13.13.0/24
